# Web
version: "3.8"

services:
  admin.j4nis05.ch:
    image: httpd:latest
    container_name: admin.j4nis05.ch
    restart: always
    volumes:
      - ./data/admin.j4nis05.ch/html:/usr/local/apache2/htdocs

  cryotea.com:
    image: j4nis05/cryotea.com
    container_name: cryotea.com
    restart: always

  j4nis05.ch:
    image: j4nis05/j4nis05.ch
    container_name: j4nis05.ch
    restart: always

  startpage:
    image: j4nis05/startpage
    container_name: startpage
    restart: always

  www.j4nis05.ch:
    image: j4nis05/www.j4nis05.ch
    container_name: www.j4nis05.ch


networks:
  default:
    external: true
    name: proxynet