# Teamspeak 5 Server
version: "3.8"
name: "ts-services"


services:
  example:
    image: 
    container_name: 
    restart: always
    ports:
      - 
    volumes:
      - 
    environment:
      - 


networks:
  default:
    external: true
    name: proxynet


volumes:
  